# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading 

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [3]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [6]:
# Import torch
import torch

# Create random tensor
tensor = torch.rand(7, 7)
tensor

tensor([[0.4681, 0.5731, 0.4625, 0.2373, 0.2990, 0.1149, 0.4780],
        [0.4102, 0.0199, 0.6959, 0.8807, 0.7939, 0.0818, 0.3590],
        [0.7528, 0.6242, 0.5656, 0.3261, 0.1406, 0.6328, 0.6501],
        [0.7355, 0.7729, 0.5552, 0.0695, 0.3081, 0.9532, 0.8508],
        [0.7760, 0.7467, 0.3536, 0.6382, 0.2566, 0.3520, 0.9280],
        [0.7122, 0.8124, 0.7580, 0.9561, 0.7858, 0.4195, 0.3481],
        [0.6741, 0.0156, 0.6399, 0.1509, 0.9234, 0.8834, 0.5235]])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [13]:
# Create another random tensor
a_tensor = torch.rand(1, 7)
# Perform matrix multiplication 
torch.mm(tensor, a_tensor.T)

tensor([[0.8655],
        [1.2723],
        [1.3605],
        [1.6905],
        [1.3750],
        [1.7969],
        [1.9329]])

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [15]:
# Set manual seed
torch.manual_seed(0)

# Create two random tensors
b_tensor = torch.rand(7, 7)
c_tensor = torch.rand(1, 7)
# Matrix multiply tensors
torch.mm(b_tensor, c_tensor.T)

tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [16]:
# Set random seed on the GPU
torch.cuda.manual_seed(1234)


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [19]:
# Set random seed
torch.manual_seed(1234)

# Check for access to GPU
if torch.cuda.is_available():
    device = torch.device("cuda")
else:
    device = torch.device("cpu")
# Create two random tensors on GPU
a_cuda_tensor = torch.rand(2, 3).to(device)
b_cuda_tensor = torch.rand(2, 3).to(device)
a_cuda_tensor, b_cuda_tensor


(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))


### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [21]:
# Perform matmul on tensor_A and tensor_B
tensor = torch.mm(a_cuda_tensor, b_cuda_tensor.T)

tensor([[0.3647, 0.4709],
        [0.5184, 0.5617]], device='cuda:0')

### 8. Find the maximum and minimum values of the output of 7.

In [24]:
# Find max
print(torch.min(tensor))
# Find min
print(torch.max(tensor))

tensor(0.3647, device='cuda:0')
tensor(0.5617, device='cuda:0')


### 9. Find the maximum and minimum index values of the output of 7.

In [25]:
# Find arg max
print(torch.argmax(tensor))

# Find arg min
print(torch.argmin(tensor)) 

tensor(3, device='cuda:0')
tensor(0, device='cuda:0')



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [28]:
# Set seed
torch.manual_seed(7)

# Create random tensor
rand_tensor = torch.rand(1,1,1,10)
print(rand_tensor, rand_tensor.shape)
# Remove single dimensions
rand_tensor = torch.squeeze(rand_tensor)
print (rand_tensor, rand_tensor.shape)
# Print out tensors and their shapes


tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
